name: "Application Deployment Pipeline"

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. Log into your Azure account securely
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    # 2. Log into your new Azure Container Registry (ACR)
    - name: Login to Azure Container Registry
      run: |
        az acr login --name bhushandevopsregistry

    # 3. Build and push your application image directly into Azure
    - name: Build and Push Docker Image
      run: |
        docker build -t bhushandevopsregistry.azurecr.io/node-app:${{ github.sha }} .
        docker push bhushandevopsregistry.azurecr.io/node-app:${{ github.sha }}

    # 4. Connect to your running AKS cluster
    - name: Connect to AKS Cluster
      uses: azure/aks-set-context@v4
      with:
        resource-group: 'devops-live-rg'
        cluster-name: 'dev-aks-cluster'

    # 5. Inject the new image version and deploy to Kubernetes nodes
    - name: Update Manifest & Deploy
      run: |
        sed -i 's|__IMAGE_PLACEHOLDER__|bhushandevopsregistry.azurecr.io/node-app:${{ github.sha }}|g' ./kubernetes/deployment.yaml
        kubectl apply -f ./kubernetes/deployment.yaml
